<?php
/**********************************************/
/* Kasseler CMS: Content Management System    */
/**********************************************/
/*                                            */
/* Copyright (c)2007-2015 by Igor Ognichenko  */
/* http://www.kasseler-cms.net/               */
/*                                            */
/**********************************************/

if (!defined('FUNC_FILE')) die('Access is limited');

global $config;
$config = array(
    'cms_version'                 => '2',
    'home_title'                  => 'Kasseler CMS',
    'http_home_url'               => 'http://kasseler2.dev/',
    'sitelogo'                    => 'includes/images/logos/5_small.png',
    'charset'                     => 'utf-8',
    'description'                 => 'Сайт построен на системе Kasseler CMS',
    'keywords'                    => 'Kasseler CMS, Forum,  Движок, PHP, Дизайн',
    'user_cookies'                => '5FIq6zo8HrlWntB_user',
    'admin_cookies'               => '0PWiYzKNGHh5fak_admin',
    'GMT_correct'                 => '+0',
    'rewrite'                     => '',
    'separator_rewrite'           => '/',
    'file_rewrite'                => '.html',
    'separator'                   => '»',
    'multilanguage'               => 'on',
    'default_module'              => 'news',
    'language'                    => 'russian',
    'template'                    => 'kasseler2',
    'case_template'               => 'on',
    'disable_site'                => '',
    'disable_description'         => '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\"><head><title>Сайт закрыт</title><meta http-equiv=\\\'content-type\\\' content=\\\'text/html; charset=utf-8\\\' /><link rel=\\\'stylesheet\\\' type=\\\'text/css\\\' href=\\\'includes/css/errors.css\\\' media=\\\'screen\\\' /></head><body class=\\\'bg_body\\\'><br /><br /><br /><br /><br /><br /><br /><br /><div align=\\\'center\\\'><img src=\\\'includes/images/logos/logo_kasseler.png\\\' alt=\\\'Kasseler CMS\\\'/></div><div align=\\\'center\\\'>Сайт находится на реконструкции, после завершения всех работ сайт будет открыт.<br />Приносим вам свои извинения за доставленные неудобства.</div></body></html>',
    'admin_mail'                  => 'admin@kasseler2.loc',
    'contact_mail'                => 'support@kasseler2.loc',
    'sends_mail'                  => 'info@kasseler2.loc',
    'charset_mail'                => 'utf-8',
    'template_mail'               => 'includes/template/mail.tpl',
    'site_name_for_mail'          => 'Kasseler CMS',
    'type_emeils'                 => 'text/html',
    'bcc_send'                    => 'on',
    'type_email_send'             => 'mail',
    'smtp_host'                   => 'smtp.gmail.com',
    'smtp_port'                   => '465',
    'smtp_user'                   => 'noreply@hostname.com',
    'smtp_password'               => '',
    'smtp_ssl'                    => '',
    'send_mail'                   => 'on',
    'adminfile'                   => 'admin.php',
    'logined_admin'               => '0',
    'capcha_symbols'              => '0123456789',
    'capcha_count_symbols'        => '3-4',
    'time_of_life_session'        => '365',
    'time_online'                 => '300',
    'interval_session_update'     => '150',
    'date_format'                 => 'd.m.Y',
    'classes_links'               => 'sys_link,account_ico,module_navi_sel,module_navi,list_link',
    'gzlevel'                     => '8',
    'gz'                          => 'on',
    'geoip'                       => '',
    'ajaxload'                    => '',
    'mark'                        => '1',
    'mark_img'                    => 'includes/images/mark.png',
    'htmlTags'                    => 'b,i,u,hr,li',
    'typeEditor'                  => '1',
    'variables'                   => '2',
    'query'                       => '2',
    'mode_debugging_php'          => 'on',
    'mode_debugging_sql'          => 'on',
    'mode_debugging_http'         => 'on',
    'log_debugging_php'           => 'on',
    'log_debugging_sql'           => 'on',
    'log_debugging_http'          => 'on',
    'log_emails_send'             => 'on',
    'log_error_user_logined'      => '',
    'filrer_referer'              => '',
    'pdaversion'                  => '',
    'imgpdaversion'               => '',
    'download_resume'             => '',
    'download_speed'              => '1024',
    'install_date'                => '2015-01-31',
    'user_agent_full'             => '',
    'whois'                       => 'http://www.kasseler-cms.net/index.php?module=whois&amp;ip=',
    'compatibility'               => '',
    'jquery'                      => 'local',
    'licence_file'                => 'KR.000001.xml',
    'send_pmr'                    => '',
    'module_br'                   => 'account,albom,audio,contact,faq,files,forum,jokes,media,news,pages,radio,recommend,search,shop,static,top_site,top_users,voting',
    'method_br'                   => '0',
    'xhtmleditor_g'               => '',
    'captcha_free'                => '',
    'ratings'                     => 'on'
);
