"use strict";
var wkr_lang_ru = {
   bold : 'Полужирный',
   italic : 'Курсив',
   underline : 'Подчеркнутый',
   strikethrough : 'Перечеркнутый',
   justifyleft : 'По левому краю',
   justifycenter : 'По центру',
   justifyright : 'По правому краю',
   justifyFull : 'По ширине',
   insertUnorderedList : 'Маркированный список',
   insertOrderedList : 'Цыфровой список',
   indent : 'Увеличить отступ',
   outdent : 'Уменьшить отступ',
   subscript : 'Подстрочный',
   superscript : 'Надстрочный',
   insertHorizontalRule : 'Тэг HR',
   selectFont : 'Шрифт',
   selectSize : 'Выбрать размер шрифта',
   foreColor : 'Цвет шрифта',
   smiles : 'Добавить смайл',
   insertImage : 'Добавить рисунок',
   createLink : 'Добавить ссылку',
   removeLink : 'Удалить ссылку',
   insertCode : 'Код',
   insertQuote : 'Цитата',
   insertHide : 'Скрытый текст',
   translit : 'Вставить транслит',
   preview : 'Предварительный просмотр',
   charMap : 'Вставить символ',
   backColor : 'Цвет заливки',
   attach : 'Прикрепить файл',
   spoiler : 'Спойлер',
   undo : 'Отменить действие',
   redo : 'Вернуть действие', 
   
   text : 'Текст', 
   img_align: 'Выравнивание',
   img_title: 'Заголовок',
   img_url: 'Ссылка на рисунок',
   img_upload: 'Загрузить рисунок',
   Link:'Ссылка',
   Smiles:'Добавить смайл',
   spoiler_text:'Скрытое содержимое',
   spoiler_count:'Количество сообщений',
   htmlcode:'HTML содержимое',   
   codeType: 'Тип',
   codeShow: 'Показать код',
}
varInited('wkr_init_lang',function(){wkr_init_lang(wkr_lang_ru)});
