"use strict";
(function () {
   var mapchar = $.wkr_editor.defaults.plugins.mapchar = [
      ['&#160;','&nbsp;','no-break space'],
      ['&#38;','&amp;','ampersand'],
      ['&#34;','&quot;','quotation mark'],
      // finance
      ['&#162;','&cent;','cent sign'],
      ['&#8364;','&euro;','euro sign'],
      ['&#163;','&pound;','pound sign'],
      ['&#165;','&yen;','yen sign'],
      // signs
      ['&#169;','&copy;','copyright sign'],
      ['&#174;','&reg;','registered sign'],
      ['&#8482;','&trade;','trade mark sign'],
      ['&#8240;','&permil;','per mille sign'],
      ['&#181;','&micro;','micro sign'],
      ['&#183;','&middot;','middle dot'],
      ['&#8226;','&bull;','bullet'],
      ['&#8230;','&hellip;','three dot leader'],
      ['&#8242;','&prime;','minutes / feet'],
      ['&#8243;','&Prime;','seconds / inches'],
      ['&#167;','&sect;','section sign'],
      ['&#182;','&para;','paragraph sign'],
      ['&#223;','&szlig;','sharp s / ess-zed'],
      // quotations
      ['&#8249;','&lsaquo;','single left-pointing angle quotation mark'],
      ['&#8250;','&rsaquo;','single right-pointing angle quotation mark'],
      ['&#171;','&laquo;','left pointing guillemet'],
      ['&#187;','&raquo;','right pointing guillemet'],
      ['&#8216;','&lsquo;','left single quotation mark'],
      ['&#8217;','&rsquo;','right single quotation mark'],
      ['&#8220;','&ldquo;','left double quotation mark'],
      ['&#8221;','&rdquo;','right double quotation mark'],
      ['&#8218;','&sbquo;','single low-9 quotation mark'],
      ['&#8222;','&bdquo;','double low-9 quotation mark'],
      ['&#60;','&lt;','less-than sign'],
      ['&#62;','&gt;','greater-than sign'],
      ['&#8804;','&le;','less-than or equal to'],
      ['&#8805;','&ge;','greater-than or equal to'],
      ['&#8211;','&ndash;','en dash'],
      ['&#8212;','&mdash;','em dash'],
      ['&#175;','&macr;','macron'],
      ['&#8254;','&oline;','overline'],
      ['&#164;','&curren;','currency sign'],
      ['&#166;','&brvbar;','broken bar'],
      ['&#168;','&uml;','diaeresis'],
      ['&#161;','&iexcl;','inverted exclamation mark'],
      ['&#191;','&iquest;','turned question mark'],
      ['&#710;','&circ;','circumflex accent'],
      ['&#732;','&tilde;','small tilde'],
      ['&#176;','&deg;','degree sign'],
      ['&#8722;','&minus;','minus sign'],
      ['&#177;','&plusmn;','plus-minus sign'],
      ['&#247;','&divide;','division sign'],
      ['&#8260;','&frasl;','fraction slash'],
      ['&#215;','&times;','multiplication sign'],
      ['&#185;','&sup1;','superscript one'],
      ['&#178;','&sup2;','superscript two'],
      ['&#179;','&sup3;','superscript three'],
      ['&#188;','&frac14;','fraction one quarter'],
      ['&#189;','&frac12;','fraction one half'],
      ['&#190;','&frac34;','fraction three quarters'],
      // math / logical
      ['&#402;','&fnof;','function / florin'],
      ['&#8747;','&int;','integral'],
      ['&#8721;','&sum;','n-ary sumation'],
      ['&#8734;','&infin;','infinity'],
      ['&#8730;','&radic;','square root'],
      ['&#8764;','&sim;','similar to'],
      ['&#8773;','&cong;','approximately equal to'],
      ['&#8776;','&asymp;','almost equal to'],
      ['&#8800;','&ne;','not equal to'],
      ['&#8801;','&equiv;','identical to'],
      ['&#8712;','&isin;','element of'],
      ['&#8713;','&notin;','not an element of'],
      ['&#8715;','&ni;','contains as member'],
      ['&#8719;','&prod;','n-ary product'],
      ['&#8743;','&and;','logical and'],
      ['&#8744;','&or;','logical or'],
      ['&#172;','&not;','not sign'],
      ['&#8745;','&cap;','intersection'],
      ['&#8746;','&cup;','union'],
      ['&#8706;','&part;','partial differential'],
      ['&#8704;','&forall;','for all'],
      ['&#8707;','&exist;','there exists'],
      ['&#8709;','&empty;','diameter'],
      ['&#8711;','&nabla;','backward difference'],
      ['&#8727;','&lowast;','asterisk operator'],
      ['&#8733;','&prop;','proportional to'],
      ['&#8736;','&ang;','angle'],
      // undefined
      ['&#180;','&acute;','acute accent'],
      ['&#184;','&cedil;','cedilla'],
      ['&#170;','&ordf;','feminine ordinal indicator'],
      ['&#186;','&ordm;','masculine ordinal indicator'],
      ['&#8224;','&dagger;','dagger'],
      ['&#8225;','&Dagger;','double dagger'],
      // alphabetical special chars
      ['&#192;','&Agrave;','A - grave'],
      ['&#193;','&Aacute;','A - acute'],
      ['&#194;','&Acirc;','A - circumflex'],
      ['&#195;','&Atilde;','A - tilde'],
      ['&#196;','&Auml;','A - diaeresis'],
      ['&#197;','&Aring;','A - ring above'],
      ['&#198;','&AElig;','ligature AE'],
      ['&#199;','&Ccedil;','C - cedilla'],
      ['&#200;','&Egrave;','E - grave'],
      ['&#201;','&Eacute;','E - acute'],
      ['&#202;','&Ecirc;','E - circumflex'],
      ['&#203;','&Euml;','E - diaeresis'],
      ['&#204;','&Igrave;','I - grave'],
      ['&#205;','&Iacute;','I - acute'],
      ['&#206;','&Icirc;','I - circumflex'],
      ['&#207;','&Iuml;','I - diaeresis'],
      ['&#208;','&ETH;','ETH'],
      ['&#209;','&Ntilde;','N - tilde'],
      ['&#210;','&Ograve;','O - grave'],
      ['&#211;','&Oacute;','O - acute'],
      ['&#212;','&Ocirc;','O - circumflex'],
      ['&#213;','&Otilde;','O - tilde'],
      ['&#214;','&Ouml;','O - diaeresis'],
      ['&#216;','&Oslash;','O - slash'],
      ['&#338;','&OElig;','ligature OE'],
      ['&#352;','&Scaron;','S - caron'],
      ['&#217;','&Ugrave;','U - grave'],
      ['&#218;','&Uacute;','U - acute'],
      ['&#219;','&Ucirc;','U - circumflex'],
      ['&#220;','&Uuml;','U - diaeresis'],
      ['&#221;','&Yacute;','Y - acute'],
      ['&#376;','&Yuml;','Y - diaeresis'],
      ['&#222;','&THORN;','THORN'],
      ['&#224;','&agrave;','a - grave'],
      ['&#225;','&aacute;','a - acute'],
      ['&#226;','&acirc;','a - circumflex'],
      ['&#227;','&atilde;','a - tilde'],
      ['&#228;','&auml;','a - diaeresis'],
      ['&#229;','&aring;','a - ring above'],
      ['&#230;','&aelig;','ligature ae'],
      ['&#231;','&ccedil;','c - cedilla'],
      ['&#232;','&egrave;','e - grave'],
      ['&#233;','&eacute;','e - acute'],
      ['&#234;','&ecirc;','e - circumflex'],
      ['&#235;','&euml;','e - diaeresis'],
      ['&#236;','&igrave;','i - grave'],
      ['&#237;','&iacute;','i - acute'],
      ['&#238;','&icirc;','i - circumflex'],
      ['&#239;','&iuml;','i - diaeresis'],
      ['&#240;','&eth;','eth'],
      ['&#241;','&ntilde;','n - tilde'],
      ['&#242;','&ograve;','o - grave'],
      ['&#243;','&oacute;','o - acute'],
      ['&#244;','&ocirc;','o - circumflex'],
      ['&#245;','&otilde;','o - tilde'],
      ['&#246;','&ouml;','o - diaeresis'],
      ['&#248;','&oslash;','o slash'],
      ['&#339;','&oelig;','ligature oe'],
      ['&#353;','&scaron;','s - caron'],
      ['&#249;','&ugrave;','u - grave'],
      ['&#250;','&uacute;','u - acute'],
      ['&#251;','&ucirc;','u - circumflex'],
      ['&#252;','&uuml;','u - diaeresis'],
      ['&#253;','&yacute;','y - acute'],
      ['&#254;','&thorn;','thorn'],
      ['&#255;','&yuml;','y - diaeresis'],
      ['&#913;','&Alpha;','Alpha'],
      ['&#914;','&Beta;','Beta'],
      ['&#915;','&Gamma;','Gamma'],
      ['&#916;','&Delta;','Delta'],
      ['&#917;','&Epsilon;','Epsilon'],
      ['&#918;','&Zeta;','Zeta'],
      ['&#919;','&Eta;','Eta'],
      ['&#920;','&Theta;','Theta'],
      ['&#921;','&Iota;','Iota'],
      ['&#922;','&Kappa;','Kappa'],
      ['&#923;','&Lambda;','Lambda'],
      ['&#924;','&Mu;','Mu'],
      ['&#925;','&Nu;','Nu'],
      ['&#926;','&Xi;','Xi'],
      ['&#927;','&Omicron;','Omicron'],
      ['&#928;','&Pi;','Pi'],
      ['&#929;','&Rho;','Rho'],
      ['&#931;','&Sigma;','Sigma'],
      ['&#932;','&Tau;','Tau'],
      ['&#933;','&Upsilon;','Upsilon'],
      ['&#934;','&Phi;','Phi'],
      ['&#935;','&Chi;','Chi'],
      ['&#936;','&Psi;','Psi'],
      ['&#937;','&Omega;','Omega'],
      ['&#945;','&alpha;','alpha'],
      ['&#946;','&beta;','beta'],
      ['&#947;','&gamma;','gamma'],
      ['&#948;','&delta;','delta'],
      ['&#949;','&epsilon;','epsilon'],
      ['&#950;','&zeta;','zeta'],
      ['&#951;','&eta;','eta'],
      ['&#952;','&theta;','theta'],
      ['&#953;','&iota;','iota'],
      ['&#954;','&kappa;','kappa'],
      ['&#955;','&lambda;','lambda'],
      ['&#956;','&mu;','mu'],
      ['&#957;','&nu;','nu'],
      ['&#958;','&xi;','xi'],
      ['&#959;','&omicron;','omicron'],
      ['&#960;','&pi;','pi'],
      ['&#961;','&rho;','rho'],
      ['&#962;','&sigmaf;','final sigma'],
      ['&#963;','&sigma;','sigma'],
      ['&#964;','&tau;','tau'],
      ['&#965;','&upsilon;','upsilon'],
      ['&#966;','&phi;','phi'],
      ['&#967;','&chi;','chi'],
      ['&#968;','&psi;','psi'],
      ['&#969;','&omega;','omega'],
      // symbols
      ['&#8501;','&alefsym;','alef symbol'],
      ['&#982;','&piv;','pi symbol'],
      ['&#8476;','&real;','real part symbol'],
      ['&#977;','&thetasym;','theta symbol'],
      ['&#978;','&upsih;','upsilon - hook symbol'],
      ['&#8472;','&weierp;','Weierstrass p'],
      ['&#8465;','&image;','imaginary part'],
      // arrows
      ['&#8592;','&larr;','leftwards arrow'],
      ['&#8593;','&uarr;','upwards arrow'],
      ['&#8594;','&rarr;','rightwards arrow'],
      ['&#8595;','&darr;','downwards arrow'],
      ['&#8596;','&harr;','left right arrow'],
      ['&#8629;','&crarr;','carriage return'],
      ['&#8656;','&lArr;','leftwards double arrow'],
      ['&#8657;','&uArr;','upwards double arrow'],
      ['&#8658;','&rArr;','rightwards double arrow'],
      ['&#8659;','&dArr;','downwards double arrow'],
      ['&#8660;','&hArr;','left right double arrow'],
      ['&#8756;','&there4;','therefore'],
      ['&#8834;','&sub;','subset of'],
      ['&#8835;','&sup;','superset of'],
      ['&#8836;','&nsub;','not a subset of'],
      ['&#8838;','&sube;','subset of or equal to'],
      ['&#8839;','&supe;','superset of or equal to'],
      ['&#8853;','&oplus;','circled plus'],
      ['&#8855;','&otimes;','circled times'],
      ['&#8869;','&perp;','perpendicular'],
      ['&#8901;','&sdot;','dot operator'],
      ['&#8968;','&lceil;','left ceiling'],
      ['&#8969;','&rceil;','right ceiling'],
      ['&#8970;','&lfloor;','left floor'],
      ['&#8971;','&rfloor;','right floor'],
      ['&#9001;','&lang;','left-pointing angle bracket'],
      ['&#9002;','&rang;','right-pointing angle bracket'],
      ['&#9674;','&loz;','lozenge'],
      ['&#9824;','&spades;','black spade suit'],
      ['&#9827;','&clubs;','black club suit'],
      ['&#9829;','&hearts;','black heart suit'],
      ['&#9830;','&diams;','black diamond suit']
   ];
   var cont;
   var crtl = false;
   var plugin = $.wkr_editor.plugins['mapchar']={
      create:function(editor, button, a){
         cont = $('<div/>',{'class':'dropdown-menu mapchar', style: 'padding:5px', title: ' '});
         a.append(cont).attr('data-toggle','dropdown');
         cont.on('mouseenter','.char',function(){
            var info = $(this).addClass('focus').data('info');
            cont.find('.charview').html(info[1]);
            cont.find('.iline').html(info[2]);
         }).on('mouseleave','.char',function(){
            $(this).removeClass('focus');
         }).on('click','.char',function(even){
            var info = $(this).data('info');
            even.stopPropagation();
            even.preventDefault();
            if(!even.ctrlKey) cont.hide();
            else crtl = true;
            $.wkr_editor.lasteditor.focus(); $.wkr_editor.cmd.restoreSelection(false);
            $.wkr_editor.cmd.textInsert(info[1]);
         });
         $(document).on('keyup.mapchar',function(even){
            if(crtl && !even.ctrlKey){cont.hide();crtl = false;}
         })
         plugin.init();
      },
      command:function(cmd){
      },
      show:function(){
         crtl = false;
      },
      init:function(){
         cont.children().remove();
         var dc = $('<div/>',{style:"display: inline-block;"}).appendTo(cont);
         for(var i=0;i<mapchar.length;i++){
            $('<div/>',{html: mapchar[i][0],'class':'char'}).data('info', mapchar[i]).appendTo(dc);
            if((i+1) % 18==0) $('<br/>').appendTo(dc);
         }
         var dcv = $('<div/>',{style:'display: inline-block; width: 100px; vertical-align: top; margin-top: 20%;', text:' '}).appendTo(cont);
         $('<div/>',{'class':'charview', style:'line-height: 100px;'}).appendTo(dcv);
         $('<div/>',{'class':'iline'}).appendTo(dcv);
      }
   }
})();
$.wkr_editor.defaults.buttons['mapchar'] = {title: 'charMap',className: 'icon-char', plugin:$.wkr_editor.plugins['mapchar']};
